\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r Setup, include=FALSE}
# Set your working directory

# Load your packages
install.packages('readxl')
install.packages('foreign')
install.packages('sf')
install.packages('leaflet')
install.packages('mapview')
library(readxl)
library(here)
library(tidyverse)
library(lubridate)
library(foreign)
library(dplyr)
library(tidyverse, quietly = TRUE)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)

# Set your ggplot theme
theme_set(theme_minimal())

# Check working directory
here()

# Load your datasets
#Importing processed energy monthly generation data
df_generation_monthly <- read.csv(here("Data/Processed/df_generation_monthly.csv"),
                                  stringsAsFactors = TRUE)
#Importing processed pollutant monthly data 
df_pollutant_monthly <- read.csv(here("Data/Processed/df_pollutant.csv"),
                                  stringsAsFactors = TRUE)

#Importing processed plant location and capacity data
df_plantcapacities_locations <- read.csv(here("Data/Processed/df_plantcapacities_locations.csv"),
                                  stringsAsFactors = TRUE)
#Importing processed pollutant observation stations data
df_station_locations <- read.csv(here("Data/Processed/df_latitude_longitude.csv"),
                                  stringsAsFactors = TRUE)
#Importing state abbreviations 
df_state<- read.csv(here("Data/Processed/df_statename.csv"),
                                  stringsAsFactors = TRUE)

#Setting date columns as date objects
df_generation_monthly$Date <- ymd(df_generation_monthly$Date)
df_pollutant_monthly$Date <- ym(df_pollutant_monthly$Date)

#Setting date columns as date objects
df_generation_monthly$Date <- ymd(df_generation_monthly$Date)
df_pollutant_monthly$Date <- ymd(df_pollutant_monthly$Date)

```


# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 
```{r Visualization: Generation}
top_states_renewables2022 <- df_generation_monthly %>% 
  filter(Year == 2022) %>% 
  group_by(State) %>% 
  summarise(NetGeneration = sum(NetGeneration)) %>% 
  mutate(Rank = rank(-NetGeneration)) %>% 
  filter(Rank %in% c(1:10))

#visualizing renewable energy generation over time

#Summarizing monthly data into annual data
df_generation_annual <- df_generation_monthly %>% 
  group_by(Year) %>% 
  summarise(NetGeneration = sum(NetGeneration))

#Plotting out trend for top 10 states
plot.MonthlyGeneration <- df_generation_monthly %>%
  filter(State %in% top_states_renewables2022$State) %>% 
  ggplot(aes(x=Date,
             y=NetGeneration,
             color=State)) +
  geom_line() +
  labs(x="Date",
       y="Monthly Energy Generation (MWh)",
       title="Monthly Renewable Energy Generation per State (MWh)")

print(plot.MonthlyGeneration)

plot.AnnualGeneration <- df_generation_annual %>% 
  ggplot(aes(x=Year,
             y=NetGeneration)) +
  geom_line() +
  labs(x="Year",
       y="Annual Energy Generation (MWh)",
       title="Annual Renewable Energy Generation over time (MWh)")

print(plot.AnnualGeneration)
```

```{r Visualization: Pollutant CO}
# Observe air quality variation among the top 10 states in renewable energy generation
top_states_renewables2022$State
unique(df_pollutant_monthly$State)

df_pollutant_location<-merge(df_pollutant_monthly,df_state,by='State') #add state abbreviation

df_pollutant_top10<-df_pollutant_location %>%
  filter(Abbreviation %in% top_states_renewables2022$State) %>%
  arrange(Date)

#confirm the selection is correct 
top_states_renewables2022$State
unique(df_pollutant_top10$Abbreviation)

unique(df_pollutant_top10$Pollutant)
#CO
df_CO_top10<-df_pollutant_top10 %>%
  filter(Pollutant=="Carbon monoxide")

#PM2.5
df_PM2.5_top10<-df_pollutant_top10 %>%
  filter(Pollutant=="PM2.5 - Local Conditions")

#SO2
df_SO2_top10<-df_pollutant_top10 %>%
  filter(Pollutant=="Sulfur dioxide")

#NO2
df_NO2_top10<-df_pollutant_top10 %>%
  filter(Pollutant=="Nitrogen dioxide (NO2)")

#PM10
df_PM10_top10<-df_pollutant_top10 %>%
  filter(Pollutant=="PM10 Total 0-10um STP")

#plotting trend for top 10 states
plot.PM10<-ggplot(df_PM10_top10, aes(x =Date, y = Mean, color=State)) +
  geom_line()+
  labs(x="Date",y="mg/m\u00B3")+
  ggtitle("PM10 Concentration")+
  theme(plot.title = element_text(hjust = 0.5))
plot.PM10

plot.PM2.5<-ggplot(df_PM2.5_top10, aes(x =Date, y = Mean, color=State)) +
  geom_line()+
  labs(x="Date",y="mg/m\u00B3")+
  ggtitle("PM2.5 Concentration")+
  theme(plot.title = element_text(hjust = 0.5))
plot.PM2.5

plot.CO<-ggplot(df_CO_top10, aes(x =Date, y = Mean, color=State)) +
  geom_line()+
  labs(x="Date",y="Parts per million")+
  ggtitle("Carbon Monoxide Concentration")+
  theme(plot.title = element_text(hjust = 0.5))
plot.CO

plot.SO2<-ggplot(df_SO2_top10, aes(x =Date, y = Mean, color=State)) +
  geom_line()+
  labs(x="Date",y="Parts per million")+
  ggtitle("Sulfur Dioxide Concentration")+
  theme(plot.title = element_text(hjust = 0.5))
plot.SO2

plot.NO2<-ggplot(df_NO2_top10, aes(x =Date, y = Mean, color=State)) +
  geom_line()+
  labs(x="Date",y="Parts per billion")+
  ggtitle("Nitrogen Dioxide Concentration")+
  theme(plot.title = element_text(hjust = 0.5))
plot.NO2

```

```{r Time Series, message=FALSE}
PM

```

```{r Visualization: Spatial}

#Reading power plant location data into spatial dataframe
df_plantcapacities_locations_sf <- df_plantcapacities_locations %>%
  na.omit() %>% 
  filter(STATE == 'TX') %>% 
  st_as_sf(coords = c('LONG','LAT'), crs=4269)

mapview(df_plantcapacities_locations_sf,
        zcol = 'FUEL',
        cex = 'CAPACITY',
        layer.name = 'Renewable Energy Plant Locations in Texas')


#counties_sf<- st_read(here('Data/Spatial/cb_2018_us_county_20m.shp')) %>% 
#  filter(STATEFP == 48)

#colnames(counties_sf)

#
#st_crs(counties_sf) 


#
#nrow(counties_sf)

#Reveal the extent of this dataset via the st_bbox() function
#st_bbox(counties_sf)

#View the data
#head(counties_sf)

#mapView(counties_sf, zcol = "AWATER")

```


\newpage

# Analysis

```{r}
#Box Plot for Comparing Distributions of a Single Pollutant Across Multiple States:


# PM2.5
ggplot(df_PM2.5_top10, aes(x = State, y = Mean, fill = State)) +
  geom_boxplot() +
  labs(title = "Distribution of PM2.5 Levels Across States",
       x = "State",
       y = "PM2.5 Concentration (µg/m³)") +
  theme_minimal() +
  theme(legend.position = "none")

# CO

ggplot(df_CO_top10, aes(x = State, y = Mean, fill = State)) +
  geom_boxplot() +
  labs(title = "Distribution of CO Levels Across States",
       x = "State",
       y = "CO Concentration (ppm)") +
  theme_minimal() +
  theme(legend.position = "none")

# NO2

ggplot(df_NO2_top10, aes(x = State, y = Mean, fill = State)) +
  geom_boxplot() +
  labs(title = "Distribution of NO2 Levels Across States",
       x = "State",
       y = "NO2 Concentration (ppb)") +
  theme_minimal() +
  theme(legend.position = "none")

# PM10 

ggplot(df_PM10_top10, aes(x = State, y = Mean, fill = State)) +
  geom_boxplot() +
  labs(title = "Distribution of PM10 Levels Across States",
       x = "State",
       y = "PM10 Concentration (µg/m³)") +
  theme_minimal() +
  theme(legend.position = "none")

# SO2

ggplot(df_SO2_top10, aes(x = State, y = Mean, fill = State)) +
  geom_boxplot() +
  labs(title = "Distribution of SO2 Levels Across States",
       x = "State",
       y = "SO2 Concentration (ppb)") +
  theme_minimal() +
  theme(legend.position = "none")


```


```{r}
library(dplyr)

# df_generation_monthly
top_states <- df_generation_monthly %>%
  group_by(State) %>%
  summarise(TotalGeneration = sum(NetGeneration)) %>%
  top_n(10, TotalGeneration) %>%
  pull(State)

#Time Series Plot for Renewable Energy Generation
ggplot(df_generation_monthly %>% filter(State %in% top_states), 
       aes(x = Date, y = NetGeneration, group = State, color = State)) +
  geom_line() +
  labs(title = "Renewable Energy Generation Over Time in Top 10 States",
       x = "Date",
       y = "Net Generation (MWh)") +
  theme_minimal()



```

```{r}
# Check unique states in both datasets
unique(df_generation_monthly$State)
unique(df_pollutant_monthly$State)

```

```{r}
state_abbreviations <- c(AL = "Alabama", AK = "Alaska", AZ = "Arizona", AR = "Arkansas", CA = "California", 
                         CO = "Colorado", CT = "Connecticut", DE = "Delaware", FL = "Florida", GA = "Georgia", 
                         HI = "Hawaii", ID = "Idaho", IL = "Illinois", IN = "Indiana", IA = "Iowa", 
                         KS = "Kansas", KY = "Kentucky", LA = "Louisiana", ME = "Maine", MD = "Maryland", 
                         MA = "Massachusetts", MI = "Michigan", MN = "Minnesota", MS = "Mississippi", MO = "Missouri", 
                         MT = "Montana", NE = "Nebraska", NV = "Nevada", NH = "New Hampshire", NJ = "New Jersey", 
                         NM = "New Mexico", NY = "New York", NC = "North Carolina", ND = "North Dakota", 
                         OH = "Ohio", OK = "Oklahoma", OR = "Oregon", PA = "Pennsylvania", RI = "Rhode Island", 
                         SC = "South Carolina", SD = "South Dakota", TN = "Tennessee", TX = "Texas", UT = "Utah", 
                         VT = "Vermont", VA = "Virginia", WA = "Washington", WV = "West Virginia", WI = "Wisconsin", 
                         WY = "Wyoming")


df_pollutant_monthly$State <- sapply(df_pollutant_monthly$State, function(x) {
  name <- state_abbreviations[which(state_abbreviations == x)]
  if (length(name) == 0) NA else names(name)
})


df_merged_top_states <- merge(df_generation_monthly %>% filter(State %in% top_states), 
                              df_pollutant_monthly %>% filter(State %in% top_states), 
                              by = c("State", "Date"))

str(df_merged_top_states)

```
```{r}
# Creating a list of unique pollutants in our dataset
unique_pollutants <- unique(df_merged_top_states$Pollutant)

# Creating a list to store the plots
scatter_plots <- list()

# Looping through each unique pollutant and creating a scatter plot
for (pollutant in unique_pollutants) {
  plot_data <- df_merged_top_states[df_merged_top_states$Pollutant == pollutant, ]
  
  plot <- ggplot(plot_data, aes(x = NetGeneration, y = Mean, color = State)) +
    geom_point() +
    labs(title = paste("Net Generation vs.", pollutant),
         x = "Net Generation",
         y = "Pollutant Concentration",
         color = "State") +
    theme_minimal()
  
  scatter_plots[[pollutant]] <- plot
}

# Printing the scatter plots
scatter_plots


```

```{r}



```

## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
